### ISSUE TITLE
Providing an incorrectly formatted PEM formatted key hangs

### ISSUE THREAD

**Issue by Nickforall** [joken-elixir/joken#210] opened 2019-01-11 12:43 UTC
Hey there!

I have an application where we use a jwt signed with the RS256 algorithm. I accidentally provided my public key with an extra newline, which caused the VM to use 100% cpu usage, eventually leading to my http request timing out.

## Steps to reproduce

* Setup joken with a "RS256" algorithm and public key
```
config :joken,
  rs256: [
    signer_alg: "RS256",
    key_pem: File.read!("jwtRS256_tests.key.pub")
  ]
```
* Have a formatting error in your `jwtRS256_tests.key.pub`, in my case this was an extra newline
* Call this function with a correctly signed token
```
defp verify(token) do
  Joken.Signer.verify(token, Joken.Signer.parse_config(:rs256))
end
```
* The beam process will use 99% of CPU until killed

**Comment by victorolinasc** [comment] 2019-01-15 23:02
Ouch! 

Thanks for reporting. I'll be looking into that to see what is causing that... Just to be extra sure, can you provide: OS, OS version, Erlang and Elixir versions? If it is not much to ask, could you also provide which version of OpenSSL you have on your machine?

Thanks in advance!

**Comment by victorolinasc** [comment] 2019-01-15 23:11
I can't reproduce locally unfortunately. I tried this config:

```elixir
  bad_pem: [
    signer_alg: "RS256",
    key_pem: rsa_pem_key <> "\n\n" # rsa_pem_key is match from the config/test.exs file
  ]

  # then on a test I did like this:
  test "can parse badly formatted PEM" do
    assert Signer.parse_config(:bad_pem) == %Signer{
      # all of the key's detail are correct here :)
    }
  end
```

It ran instantaneously (what a difficult word to write...). After you provide your environment details I can check more things.

**Comment by Nickforall** [comment] 2019-01-15 23:11
### Better reproduction
I haven't been able to always reproduce it recently, but here is an example key that causes it
```elixir
config :joken,
  rs256: [
    signer_alg: "RS256",
    key_pem: "
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqFGbV4Hu7G2Eu14VkEtc
    VRpwb7yySAeZLUWDbGFBqZYAWLwo6Zoi5aSI2hLaNSMG5IDzkN8M465KCfSNBGwh
    rfMYVKpY+m+4greCVGehYJ4jIZuBnJxeBBMHxHOaylzjJmrUzJZ47QRz8OqHr/EU
    bdXOiLjcWwM1jiHEwxYi6IKR+XLiMwHGTLC6Ny9ASkDbuxDXDj+Z1XHw8f5LCLD5
    f12PUcwxm0T5TMt4BdmZUqWDsdBvdjTdPKS0W0S/KaFYEN+OWc06xw6LK8kkpQLo
    zLbTgI6R1QrX47oLKaaClNxBdIkdnoVJMa+goXCnWKsaexB84ZfNvws9uqOlIK0/
    aWNiUKbf0yC2dFVgXMzDu2sRfdLUlsgxRcMuSZ+gp1t2kHsPrpSywxsgmjDgkc3v
    /3SRi+8UpK4GnzWrroscTHK14l6CFS/JhRjypYEvmJjPOkrwmuiOjKLkHqxOelQg
    22z8Np9qi73lTGZBytWsjYr/VU+LYJDZxqCmCoCJ9Rivr5aPJE1whQWae4TD6v2Z
    yGVuv6Q7WMvS6WqAXCQMI7LMDdCdk9TmZu7Q9OvWcuTMlsRSoucj/vyvKPgVSxwM
    uHbRT/C7Ns5Xmgvhn+znBxaA1kmmC7hzgXPR5DaZiN/5xTtaz67DzH0XinPS0Bc5
    Tr6F3NYULDzumlnh9k4Z1a0CAwEAAQ==
    -----END PUBLIC KEY-----"
  ]
```

I have been able to reproduce both locally and in production

## Local machine
* LibreSSL 2.6.4
* Erlang: `Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]`
* Elixir 1.7.2

## Production environment
* This docker image https://github.com/bitwalker/alpine-elixir-phoenix v1.7.1

**Comment by victorolinasc** [comment] 2019-01-15 23:12
Wow that was fast! I'll look more into it now! 

Thanks

**Comment by Nickforall** [comment] 2019-01-15 23:14
Haha, no problem! Now that I think of it, I'm not 100% sure it's caused by newlines. Might also be the extra spaces.

**Comment by victorolinasc** [comment] 2019-01-15 23:19
Even using your key I couldn't reproduce it. One thing to note though is that your multi line string is a bit odd to my eyes... 

Normally I'd use `"""` and end it on the column we want it to be the first. So, it'd be like this:

```elixir
  bad_pem: [
    signer_alg: "RS256",
    key_pem: """
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqFGbV4Hu7G2Eu14VkEtc
    VRpwb7yySAeZLUWDbGFBqZYAWLwo6Zoi5aSI2hLaNSMG5IDzkN8M465KCfSNBGwh
    rfMYVKpY+m+4greCVGehYJ4jIZuBnJxeBBMHxHOaylzjJmrUzJZ47QRz8OqHr/EU
    bdXOiLjcWwM1jiHEwxYi6IKR+XLiMwHGTLC6Ny9ASkDbuxDXDj+Z1XHw8f5LCLD5
    f12PUcwxm0T5TMt4BdmZUqWDsdBvdjTdPKS0W0S/KaFYEN+OWc06xw6LK8kkpQLo
    zLbTgI6R1QrX47oLKaaClNxBdIkdnoVJMa+goXCnWKsaexB84ZfNvws9uqOlIK0/
    aWNiUKbf0yC2dFVgXMzDu2sRfdLUlsgxRcMuSZ+gp1t2kHsPrpSywxsgmjDgkc3v
    /3SRi+8UpK4GnzWrroscTHK14l6CFS/JhRjypYEvmJjPOkrwmuiOjKLkHqxOelQg
    22z8Np9qi73lTGZBytWsjYr/VU+LYJDZxqCmCoCJ9Rivr5aPJE1whQWae4TD6v2Z
    yGVuv6Q7WMvS6WqAXCQMI7LMDdCdk9TmZu7Q9OvWcuTMlsRSoucj/vyvKPgVSxwM
    uHbRT/C7Ns5Xmgvhn+znBxaA1kmmC7hzgXPR5DaZiN/5xTtaz67DzH0XinPS0Bc5
    Tr6F3NYULDzumlnh9k4Z1a0CAwEAAQ==
    -----END PUBLIC KEY-----
    """
  ]
```

Anyway, I tested both ways and they pass with flying colors on my machine. I'm trying to recall the 1.7 release cycle and I "think" there was a bug about the [beam getting stuck before 1.7.2](https://github.com/elixir-lang/elixir/releases/tag/v1.7.2). It was about compiling and about configuration and this might be triggered by Joken somewhere (I think your `File.read!/1` example would trigger this).

I think this might be your issue. Could you try to update the patch version to 1.7.2 or the latest (1.7.4)? Just to be double sure about it.

**Comment by Nickforall** [comment] 2019-01-29 09:48
Unfortunately this still happens on 1.7.4

**Comment by victorolinasc** [comment] 2019-02-02 14:15
Sorry @Nickforall. One last check:

Can you run the purely JOSE function that aprses the PEM to see if it is an issue there? We just call `JOSE.JWK.from_pem/1`.

If the error is still reproducible then we should open an issue on JOSE.

**Comment by victorolinasc** [comment] 2019-02-02 14:15
I still wasn't able to reproduce the issue here though.

**Comment by victorolinasc** [comment] 2019-09-28 14:00
@Nickforall since I could not reproduce this and there was no more activity here, I'll be closing this issue.

If you are still having this issue (please use docstrings as single quote multiline strings preserve spaces and that makes PEM invalid) feel free to re-open.

**Closed by victorolinasc** 2019-09-28 14:00 UTC
