### ISSUE TITLE
ES256 does not return

### ISSUE THREAD

**Issue by Kloenk** [joken-elixir/joken#311] opened 2021-03-27 12:26 UTC
When using a signer with an `ES256` algorithm, generate_and_sign does not return, but hangs forever.

**Comment by victorolinasc** [comment] 2021-04-04 22:58
Can you paste an example key or source code to investigate? This seems more like a crypto/OpenSSL issue.

I'd be glad to help if there is an example code

**Comment by victorolinasc** [comment] 2021-07-03 20:47
I'll be closing the issue because can't reproduce. If you can provide a reproducible project I can take a look into it.

**Closed by victorolinasc** 2021-07-03 20:47 UTC

**Comment by Kloenk** [comment] 2021-07-03 21:47
Sorry, completely forgot this. Now I'm not even sure anymore how I produced the error. Sorry for that
